### ISSUE TITLE
关于运动轨迹问题

### ISSUE THREAD

**Issue by yuzhou01** [cggos/imu_x_fusion#17]
1）IMU和视觉融合，跑你提供的数据集，/pose_orbslam是里程计数据，那个/path_orbslam的主题的消息，代表是啥？
2）如果我要跑自己路的数据集，只有里程计数据和imu数据，没有/path的主题消息，是不是没法跑出像你那种效果的轨迹图。
![1](https://user-images.githubusercontent.com/96414333/148504949-5afe8772-3976-4c58-a1f0-de171babe285.jpg)
3）还有我看vo+imu的rviz有两个轨迹，一个是真实轨迹，一个是滤波融合后的轨迹吗？

![2](https://user-images.githubusercontent.com/96414333/148504982-391d0ff7-b70e-445e-9472-6b8fec985f02.jpg)

**Comment by cggos** [comment]
@yuzhou01 

1) /path_orbslam是VO的输出在融合后世界坐标系下的轨迹
2) 算法输入就是6DoF里程计和IMU
您最好先看看代码～
