### ISSUE TITLE
关于GNSS观测H矩阵的疑问

### ISSUE THREAD

**Issue by Maxinjun** [cggos/imu_x_fusion#27]
您好，在你的代码中H矩阵的定义如下：
![图片](https://user-images.githubusercontent.com/5317388/155492671-ef272d06-e72b-4072-9905-c9524abe517d.png)
感觉上不是对delta_x的偏导数，这个定义是对x的偏导数
根据6.1.1的定义，上图的H应该是书中的Hx,是否还应该右乘X_delta_x才是完整的H矩阵
![图片](https://user-images.githubusercontent.com/5317388/155493355-140c30c5-57a5-473e-8846-2e7f0b7b5942.png)

**Comment by cggos** [comment]
@Maxinjun 你的问题中，图一和图二公式都是对delta x求导，图二的定义使用了链式法则，图一中计算没有用链式法则，利用Local扰动模型直接对delta x进行的求导

**Comment by chengwei0427** [comment]
> @Maxinjun 你的问题中，图一和图二公式都是对delta x求导，图二的定义使用了链式法则，图一中计算没有用链式法则，利用Local扰动模型直接对delta x进行的求导

@cggos 你好，
图二是使用链式法则进行求导；
图一是使用右乘扰动，进行求导，是这样吗？
观测方程：
![image](https://user-images.githubusercontent.com/20199999/165493585-f558152d-20b0-40db-b5d9-6d680c471d18.png)
状态量：
![image](https://user-images.githubusercontent.com/20199999/165493918-d3ed7c77-7352-4bfb-809f-0229831e61a7.png)

特别的，图一的求导过程，是对上述观测公式分别对每个状态量进行求导可得吗？
