### ISSUE TITLE
run ORB-SLAM2 (Stereo) + intel realsense depth camera d415 

### ISSUE THREAD

**Issue by mark-91** [cggos/imu_x_fusion#37]
Hi, is it possible to run the algorithm with intel realsense depth camera d415
And which files should I change (I mean to calibrate the camera),
Also, can I change the type of camera in the simulators (which is installed on the robot)
thanks

**Comment by cggos** [comment]
@mark-91 you should be noticed that the input of the project are raw data of IMU and 6DoF odometry
