### ISSUE TITLE
[question][help]-unable to download orbslam2_v101easy.bag

### ISSUE THREAD

**Issue by anilbommareddy** [cggos/imu_x_fusion#51]
unable to download file orbslam2_v101easy.bag-(http://gofile.me/5lGth/4XBQVLhAn)

**Comment by cggos** [comment]
@anilbommareddy try it again, the link is OK

**Comment by anilbommareddy** [comment]
thank you @cggos , I'm able open the link and while downloading file got an error "Failed server unable to connetc" on file size download btw 150-200MB
