### ISSUE TITLE
catkin error cant find Encoder.h

### ISSUE THREAD

**Issue by Revakk** [cggos/imu_x_fusion#52]
When I try to build this package I get this error:

```bash
imu_x_fusion/src/dataset/kaist_pub.cpp:14:10: fatal error: imu_x_fusion/Encoder.h: No such file or directory
   14 | #include <imu_x_fusion/Encoder.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
```
I build with command catkin_make and I am using ubuntu 20.04 with ROS noetic.

**Comment by Revakk** [comment]
I probably had some broken packages or something. Fixed by reinstalling ROS Noetic.

**Comment by kintzhao** [comment]
add_executable(kaist_pub src/dataset/kaist_pub.cpp)
target_link_libraries(kaist_pub ${catkin_LIBRARIES} ${OpenCV_LIBS})
add_dependencies(kaist_pub ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
