### ISSUE TITLE
Does it need tf btwn IMU and GNSS device

### ISSUE THREAD

**Issue by hanmmmmm** [cggos/imu_x_fusion#6]
Hi!  I tried your exmaple bag, and it works very well!   Thank you for your awesome work!  

Now I want to run it with my IMU and GPS devices, but I am not sure if the relative pose between these 2 device matter?  
And is there place in this pkg where config this tf? 

Thank you very much!

**Comment by cggos** [comment]
you can set `I_p_Gps_` in **imu_gnss_fusion_node.cpp** which means the relative position between IMU and GNSS

**Comment by munhktamir** [comment]
Hello. I have looked into the code. Should I set the extrinsic value of the IMU into I_p_Gps_ from the GNSS antenna position?

**Comment by cggos** [comment]
@munhktamir Yes, you have to set the extrinsic value `I_p_Gps_`

**Comment by munhktamir** [comment]
Thank you @cggos. One question left is the covariance of the GPS.  My GPS sends the following sentences such as GGA, RMC, HDT every 5Hz. So, GGA gives us just HDOP value. Is there any method to find out std_lat_dev, std_lon_dev, and std_alt_dev to provide **gps_msg->position_covariance.data()**?

**Comment by cggos** [comment]
@munhktamir Sorry, I am not good at GPS.
