### ISSUE TITLE
kf.h.  code error?

### ISSUE THREAD

**Issue by llxClover** [cggos/imu_x_fusion#8]
state_ptr_->cov = I_KH * P * I_KH.transpose() + K * V * K.transpose();  (line 179)

why not is = state_ptr_->cov = I_KH * P

**Comment by cggos** [comment]
@llxClover they are same but the form state_ptr_->cov = I_KH * P has poor numerical stability
![Screenshot from 2021-11-08 10-04-09](https://user-images.githubusercontent.com/5089357/140673310-02e37ec1-62d2-432f-8b79-2c48f2dfc699.png)

**Comment by llxClover** [comment]
Could you share me your PDF(the picture that you show me just now)？



---Original---
From: "Gavin ***@***.***&gt;
Date: Mon, Nov 8, 2021 10:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cggos/imu_x_fusion] kf.h.  code error? (Issue #8)




 
@llxClover they are same but the form state_ptr_-&gt;cov = I_KH * P has poor numerical stability
 
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cggos** [comment]
the Appendix A of the PDF https://www.researchgate.net/publication/351246047_Formula_Derivation_and_Code_Analysis_of_S-MSCKF

**Comment by llxClover** [comment]
Thank you！



---Original---
From: "Gavin ***@***.***&gt;
Date: Mon, Nov 8, 2021 10:15 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cggos/imu_x_fusion] kf.h.  code error? (Issue #8)




 
the Appendix A of the PDF https://www.researchgate.net/publication/351246047_Formula_Derivation_and_Code_Analysis_of_S-MSCKF
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
